version: '3.5'
services:
  mssql-db:
    image: microsoft/mssql-server-linux:latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: password!1
    ports:
    - 1430:1433
    container_name: bigdata-cluster-mssql-db
    networks:
      - bigdata-cluster-network
  mssql-db-data-load :
    image:  muchachopolo/hadoop-complete:docker-bigdata_mssql-db-data-load
    command: sh -c './wait-for-it.sh mssql-db:1433 --timeout=0 --strict -- sleep 10 && ./run-data-load.sh'
    container_name: bigdata-cluster-mssql-db-data-load
    depends_on:
      - "mssql-db"
    networks:
      - bigdata-cluster-network
  bigdata-cluster:
    image: muchachopolo/hadoop-complete:bigdata-cluster
    restart: always
    container_name: bigdata-cluster
    command: sh -c './start-ecosystem.sh'
    depends_on:
      - mssql-db
    ports:
    - "2222:22"
    - "50070:50070"
    - "8088:8088"
    - "19888:19888"
    - "8080:8080"
    networks:
      - bigdata-cluster-network
  jupiter-cluster:
    image: muchachopolo/hadoop-complete:jupiter-cluster
    restart: always
    container_name: jupiter-cluster
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
    volumes:
      - ./jupiter-workspace:/home/jovyan
    networks:
      - bigdata-cluster-network
networks:
  bigdata-cluster-network:
    name : bigdata-cluster-network
