# -*- coding: utf-8 -*-
"""WordCloud_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16C3c-WBvvtjyR-YkIIcTIz8Yms0brc4S
"""

import matplotlib.pyplot as plt
from wordcloud import WordCloud, STOPWORDS

import re

documento_txt = open('./Test1.txt', 'r') 
texto = documento_txt.read().lower()

def random_color_func(word=None, font_size=None, position=None, orientation=None, font_path=None, random_state=None):
    h = int(360.0 * 45.0 / 255.0)
    s = int(100.0 * 255.0 / 255.0)
    l = int(100.0 * float(random_state.randint(60, 120)) / 255.0)

    return "hsl({}, {}%, {}%)".format(h, s, l)

wordcloud = WordCloud(font_path = './MTCORSVA.TTF',
                            stopwords = STOPWORDS,
                            background_color = 'white',
                            width = 1200,
                            height = 1000,
                            color_func = random_color_func
                            ).generate(texto)

plt.imshow(wordcloud)
plt.axis('off')
plt.show()

palabras = {}

pattern = re.findall(r'\b[a-z]{2,25}\b', texto)

for palabra in pattern:
  recuento = palabras.get(palabra,0)
  palabras[palabra] = recuento + 1

df_palabras = pd.DataFrame.from_dict(frequency, orient='index',columns=['Recuento'])
df_palabras.reset_index(level=0, inplace=True)
df_palabras.rename({'index': 'Palabra'},axis=1, inplace=True)
print('TOP TEN RECUENTO DE PALABRAS\n')
print(df_palabras.sort_values(by=['Recuento'],ascending=False).head(10),'\n\n')

print('ESTADÍSTICAS BÁSICAS\n')
print(df_palabras.describe(),'\n\n')

print(df_palabras.info())